// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostContentGenerateParams creates a new PostContentGenerateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostContentGenerateParams() *PostContentGenerateParams {
	return &PostContentGenerateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostContentGenerateParamsWithTimeout creates a new PostContentGenerateParams object
// with the ability to set a timeout on a request.
func NewPostContentGenerateParamsWithTimeout(timeout time.Duration) *PostContentGenerateParams {
	return &PostContentGenerateParams{
		timeout: timeout,
	}
}

// NewPostContentGenerateParamsWithContext creates a new PostContentGenerateParams object
// with the ability to set a context for a request.
func NewPostContentGenerateParamsWithContext(ctx context.Context) *PostContentGenerateParams {
	return &PostContentGenerateParams{
		Context: ctx,
	}
}

// NewPostContentGenerateParamsWithHTTPClient creates a new PostContentGenerateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostContentGenerateParamsWithHTTPClient(client *http.Client) *PostContentGenerateParams {
	return &PostContentGenerateParams{
		HTTPClient: client,
	}
}

/*
PostContentGenerateParams contains all the parameters to send to the API endpoint

	for the post content generate operation.

	Typically these are written to a http.Request.
*/
type PostContentGenerateParams struct {

	/* Attachment.

	   The file to parse.
	*/
	Attachment runtime.NamedReadCloser

	/* Schema.

	   The JSON schema that will be returned in the response.
	*/
	Schema string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post content generate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostContentGenerateParams) WithDefaults() *PostContentGenerateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post content generate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostContentGenerateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post content generate params
func (o *PostContentGenerateParams) WithTimeout(timeout time.Duration) *PostContentGenerateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post content generate params
func (o *PostContentGenerateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post content generate params
func (o *PostContentGenerateParams) WithContext(ctx context.Context) *PostContentGenerateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post content generate params
func (o *PostContentGenerateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post content generate params
func (o *PostContentGenerateParams) WithHTTPClient(client *http.Client) *PostContentGenerateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post content generate params
func (o *PostContentGenerateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttachment adds the attachment to the post content generate params
func (o *PostContentGenerateParams) WithAttachment(attachment runtime.NamedReadCloser) *PostContentGenerateParams {
	o.SetAttachment(attachment)
	return o
}

// SetAttachment adds the attachment to the post content generate params
func (o *PostContentGenerateParams) SetAttachment(attachment runtime.NamedReadCloser) {
	o.Attachment = attachment
}

// WithSchema adds the schema to the post content generate params
func (o *PostContentGenerateParams) WithSchema(schema string) *PostContentGenerateParams {
	o.SetSchema(schema)
	return o
}

// SetSchema adds the schema to the post content generate params
func (o *PostContentGenerateParams) SetSchema(schema string) {
	o.Schema = schema
}

// WriteToRequest writes these params to a swagger request
func (o *PostContentGenerateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param attachment
	if err := r.SetFileParam("attachment", o.Attachment); err != nil {
		return err
	}

	// form param schema
	frSchema := o.Schema
	fSchema := frSchema
	if fSchema != "" {
		if err := r.SetFormParam("schema", fSchema); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
