// Code generated by go-swagger; DO NOT EDIT.

package content

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGenerateContentParams creates a new GenerateContentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateContentParams() *GenerateContentParams {
	return &GenerateContentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateContentParamsWithTimeout creates a new GenerateContentParams object
// with the ability to set a timeout on a request.
func NewGenerateContentParamsWithTimeout(timeout time.Duration) *GenerateContentParams {
	return &GenerateContentParams{
		timeout: timeout,
	}
}

// NewGenerateContentParamsWithContext creates a new GenerateContentParams object
// with the ability to set a context for a request.
func NewGenerateContentParamsWithContext(ctx context.Context) *GenerateContentParams {
	return &GenerateContentParams{
		Context: ctx,
	}
}

// NewGenerateContentParamsWithHTTPClient creates a new GenerateContentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateContentParamsWithHTTPClient(client *http.Client) *GenerateContentParams {
	return &GenerateContentParams{
		HTTPClient: client,
	}
}

/*
GenerateContentParams contains all the parameters to send to the API endpoint

	for the generate content operation.

	Typically these are written to a http.Request.
*/
type GenerateContentParams struct {

	/* Attachment.

	   The file to parse.
	*/
	Attachment runtime.NamedReadCloser

	/* Schema.

	   The JSON schema that will be returned in the response.
	*/
	Schema string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateContentParams) WithDefaults() *GenerateContentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateContentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate content params
func (o *GenerateContentParams) WithTimeout(timeout time.Duration) *GenerateContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate content params
func (o *GenerateContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate content params
func (o *GenerateContentParams) WithContext(ctx context.Context) *GenerateContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate content params
func (o *GenerateContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate content params
func (o *GenerateContentParams) WithHTTPClient(client *http.Client) *GenerateContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate content params
func (o *GenerateContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttachment adds the attachment to the generate content params
func (o *GenerateContentParams) WithAttachment(attachment runtime.NamedReadCloser) *GenerateContentParams {
	o.SetAttachment(attachment)
	return o
}

// SetAttachment adds the attachment to the generate content params
func (o *GenerateContentParams) SetAttachment(attachment runtime.NamedReadCloser) {
	o.Attachment = attachment
}

// WithSchema adds the schema to the generate content params
func (o *GenerateContentParams) WithSchema(schema string) *GenerateContentParams {
	o.SetSchema(schema)
	return o
}

// SetSchema adds the schema to the generate content params
func (o *GenerateContentParams) SetSchema(schema string) {
	o.Schema = schema
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param attachment
	if err := r.SetFileParam("attachment", o.Attachment); err != nil {
		return err
	}

	// form param schema
	frSchema := o.Schema
	fSchema := frSchema
	if fSchema != "" {
		if err := r.SetFormParam("schema", fSchema); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
